# Generated by Django 5.2.7 on 2025-10-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='creado_en',
        ),
    ]
