# Generated by Django 5.1.4 on 2025-03-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='address',
        ),
    ]
