# Generated by Django 5.1.4 on 2025-03-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0004_remove_appointment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
